### ISSUE TITLE
circular polarization

### ISSUE THREAD

**Issue by yimuchunshu** [elerac/PolarizationImaging#1]
if have to consider circular polarization ,how to modify the code to calculate 4x4 Mueller matrix with circular polarizer

**Comment by elerac** [comment]
Hi, @yimuchunshu!

I am focusing on circular polarization and would like to extend the program to handle all polarization states.
I'm trying to develop the code to handle circular polarization (see [circular branch](https://github.com/elerac/polanalyser/tree/circular)). But the calculation of the 4x4 Mueller matrix is not yet available. Currently, I am very busy, so development is temporarily suspended.

To calculate the 4x4 Mueller matrix, it is recommended to modify [`calcMueller`](https://github.com/elerac/polanalyser/blob/master/polanalyser/mueller.py#L3). In particular, it is the matrix [`A`](https://github.com/elerac/polanalyser/blob/master/polanalyser/mueller.py#L25) that is to be modified. `A` is determined by the light source and the camera side polarization elements and represents the relationship between the Mueller matrix and the captured intensity. So you should rewrite `A` to take into account the effect of the both linear and circular polarizers used for the measurement.

For your reference, here is how to calculate the 3x3 Mueller matrix.
The relationship between the polarizer angles (_theta_light_, _theta_camera_), the intensity (_i_), and the Mueller matrix (**_M_1d_**) is expressed in matrix form as
&nbsp; _i_ = **_a_** **_M_1d_**
and 
&nbsp; **_a_** = [1, cos(_theta_light_), sin(_theta_light_), cos(_theta_camera_), cos(_theta_camera_)*cos(_theta_light_), cos(_theta_camera_)*sin(_theta_light_), sin(_theta_camera_), sin(_theta_camera_)*cos(_theta_light_), sin(_theta_camera_)*sin(_theta_light_)].T (1x9)
&nbsp; **_M_1d_** = [m11, m12, m13, m21, m22, m23, m31, m32, m33] (9x1)
Considering the combination of several angles, it can be extended to
&nbsp; **_I_** = **_A_** **_M_1d_**
and
&nbsp; **_I_**   = [_i1_, _i2_, ... , _iN_] (Nx1)
&nbsp; **_A_** = [**_a1_**, **_a2_**, ... , **_aN_**] (Nx9)
All that remains is to solve the least-squares problem using a pseudo-inverse matrix.
&nbsp; **_M_1d_** = **_Apinv_** **_I_**

**Comment by yimuchunshu** [comment]
Thank you very much,

**Comment by elerac** [comment]
I have updated this project to v2.0.0. It can calculate the 4x4 Mueller matrix. If you remember, please check it!

**Comment by yimuchunshu** [comment]
Thanks a lot

**Comment by yimuchunshu** [comment]
> I have updated this project to v2.0.0. It can calculate the 4x4 Mueller matrix. If you remember, please check it!

i do remember
